title: Utkarsh Kumar
description: I am currently pursuing my M.S. degree in Computer Science from NYU, Courant School of Mathematical Sciences, and offer 3.5 years of professional experience in the software industry with a focus on enterprise-level web applications, single-page applications, and progressive-web applications. Apart from my technical skills, I carry a good understanding of UI/UX and thrive on improving online products by understanding user behaviour.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect