title: Utkarsh Kumar
description: I build enterprise applications. 
Currently pursuing MS in Computer Science at New York University.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect